### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by RatulMaharaj** [f1stuff/f1-live-data#1]
Hi @f1stuff - this is a really awesome project! 

I've managed to get it up and running on macOS. I can see some historic data already, but am really keen to test the live timing in a little bit for the Miami Quali. Would love to contribute to the development of this project if you have any ideas or need help with anything. 

Wanted to also suggest that you set up github discussions for this repo - just to maybe get a conversation going :)

Thanks

**Comment by Felice-Copp56** [comment]
Hi, I have a question. I want to do a project like this (a dashboard with real time data and maybe team radio during the race of course) but I don't know where take the API.
So, anyone can tell me where get the API to develop this projects? Thanks

**Comment by RatulMaharaj** [comment]
Hi @Felice-Copp56, maybe check out [Fast-F1](https://github.com/theOehrly/Fast-F1)
