### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nopelol10** [f1stuff/f1-live-data#4]
yo can you help me install this and everything. im clueless.

**Comment by f1stuff** [comment]
Hi, 
the overall data flow is described in the [README.md](https://github.com/f1stuff/f1-live-data?tab=readme-ov-file#data-flow)
The project uses Grafana (you can read more about it here: https://grafana.com/docs/) and InfluxDB (https://www.influxdata.com/_resources/)

The easiest way to test the project is to wait for a f1 live session and follow the [Quickstart](https://github.com/f1stuff/f1-live-data?tab=readme-ov-file#quick-start). I used Ubuntu 20.04 with docker installed (https://docs.docker.com/engine/install/ubuntu/)

If you have no clue about the tech stack, it's best to start with a docker tutorial.
