### ISSUE TITLE
I cannot select two or more favorite drivers (top, left).

### ISSUE THREAD

**Issue by sanpei3** [f1stuff/f1-live-data#5]
I can select one driver (input "ALO")[OK]. 

However, I want to select a few drivers at the top left (input "ALO + LEC + VER"). But no lines at Lap time and Gap to leader[NG].

Input image
![image](https://github.com/f1stuff/f1-live-data/assets/10361358/08a7150b-2958-4701-a05b-3841ab56a323)

After pushing the "enter key," no lines[NG].
![image](https://github.com/f1stuff/f1-live-data/assets/10361358/d80e0da1-c598-4491-84e5-36ad4690ba16)

My question:
Please let me know the selection or input of the drivers.

**Comment by f1stuff** [comment]
I think you have to reload the page in your browser.

If you load the page without data no drivers in the list in the top left corner will be displayed:
![image](https://github.com/f1stuff/f1-live-data/assets/127250965/7458493d-b48a-44e3-a2c4-97cd79e7f1c7)

After reloading the page with data available the list is filled with the driver names and you can choose multiple drivers
![image](https://github.com/f1stuff/f1-live-data/assets/127250965/a09de40c-c80b-42e9-9224-6d66721bafb2)

**Comment by sanpei3** [comment]
Thank you for your suggestion. I can select drivers after reloading the page[OK].
